# Generated by Django 4.2.1 on 2023-08-09 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_userprofile_balance_userprofile_referal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referals', to=settings.AUTH_USER_MODEL, verbose_name='Реферал'),
        ),
    ]
