# Generated by Django 4.2.1 on 2023-07-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Мета опис')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Мета ключові слова')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
