# Generated by Django 4.2.1 on 2023-08-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_image_product'),
        ('core', '0003_page_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['index', 'name'], 'verbose_name': 'Сторінка', 'verbose_name_plural': 'Сторінки'},
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('sort', models.IntegerField(blank=True, default=-1, verbose_name='Індекс сортування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('products', models.ManyToManyField(related_name='product_sets', to='catalog.product', verbose_name='Товари')),
            ],
            options={
                'verbose_name': 'Набір товарів',
                'verbose_name_plural': 'Набори товарів',
                'ordering': ['sort', 'name'],
            },
        ),
    ]
