# Generated by Django 4.2.1 on 2023-05-21 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='сategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory', verbose_name='Категорія'),
        ),
    ]
