# Generated by Django 4.2.1 on 2023-05-21 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='photo',
            field=models.ImageField(blank=True, upload_to='blog_category_photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='article',
            name='сategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.blogcategory', verbose_name='Категорія'),
        ),
    ]
