# Generated by Django 4.2.1 on 2023-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_status_alter_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('in_progress', 'В обробці'), ('waiting_for_payment', 'Очікується оплата'), ('in_delivery', 'Відправлено'), ('completed', 'Завершено'), ('canceled', 'Скасовано')], default='in_progress', max_length=100, null=True, verbose_name='Статус'),
        ),
    ]
